//! The independent full-width proof-tree verifier (design §7b).
//!
//! Re-proves every `Win` from the emitted witness tree, sharing nothing
//! with the solver's search: no df-pn, no TT, no §2 defender-side
//! shortcuts. At attacker nodes the tree's move is regenerated by the
//! verifier's own policy code (the R3' window scan); at defender nodes
//! EVERY legal turn is applied through `GameState::place` — a defender-win
//! `Outcome` is a verification FAILURE at every AND node — a tree edge
//! recurses, and a non-edge must concretely resolve as an attacker win.
//!
//! The verifier also computes `Z_p` from scratch over the witness tree
//! (AT-1/DT-1/EP-1/T3-1 over the walk), which gate (b) compares against
//! the solver's memoised zones.

// RULE9-JUSTIFICATION: the verifier is one instrument — its per-node
// re-derivations, the non-edge resolution and the zone recomputation form
// one full-width re-proof that §7b adjudicates as a single gate; splitting
// it by node kind would replicate the walk and the zone accumulation the
// gate's zone cross-check depends on.
use pistol_core::{Coord, GameState, Player, Turn};

use pistol_solver::dfpn::ProofKind;
use pistol_solver::{EmittedNode, ProofTree, ZoneP};

/// What the verifier found.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Verdict {
    /// The tree is a full-width proof of the policy win, and the zone
    /// matches the solver's.
    Verified { zone: ZoneP },
    /// A defect, named.
    Failed(String),
}

/// Verify `tree` proves the policy win in `root`. The solver's per-node
/// zones come along for the cross-check.
pub fn verify(
    root: &GameState,
    tree: &ProofTree,
    policy: pistol_solver::AttackerPolicy,
) -> Verdict {
    let attacker = root.to_move();
    let mut work = root.clone();
    let mut nodes = std::collections::BTreeMap::new();
    for node in &tree.nodes {
        nodes.insert(node.key, node);
    }
    let mut computed = std::collections::BTreeMap::new();
    let verdict = verify_node(
        &mut work,
        attacker,
        tree.root,
        &nodes,
        &mut computed,
        policy,
    );
    match verdict {
        Ok(()) => {
            // Cross-check: every emitted node's solver zone equals the
            // verifier's computed zone.
            for node in &tree.nodes {
                let mine = computed
                    .get(&node.key)
                    .expect("the walk computed a zone for every emitted node");
                if mine != &node.zone {
                    return Verdict::Failed(format!(
                        "solver zone and verifier zone disagree at {:?}",
                        node.key
                    ));
                }
            }
            let zone = computed
                .get(&tree.root)
                .expect("the root has a computed zone")
                .clone();
            Verdict::Verified { zone }
        }
        Err(what) => Verdict::Failed(what),
    }
}

fn verify_node(
    state: &mut GameState,
    attacker: Player,
    key: pistol_core::Key128,
    nodes: &std::collections::BTreeMap<pistol_core::Key128, &EmittedNode>,
    computed: &mut std::collections::BTreeMap<pistol_core::Key128, ZoneP>,
    policy: pistol_solver::AttackerPolicy,
) -> Result<(), String> {
    if let Some(zone) = computed.get(&key) {
        let _ = zone;
        return Ok(());
    }
    let node = *nodes
        .get(&key)
        .ok_or_else(|| format!("the tree lacks the node {key:?} the walk reached"))?;
    match &node.kind {
        ProofKind::OrWinLeaf { witness } => {
            // The leaf's completing stones must actually decide the game,
            // checked by pistol-core itself.
            let mut applied = state.clone();
            let turn = witness_turn(witness);
            applied
                .make_turn(turn)
                .map_err(|error| format!("the win leaf's turn is illegal: {error}"))?;
            match applied.outcome() {
                pistol_core::Outcome::Win { winner, .. } if winner == attacker => {}
                other => return Err(format!("the win leaf does not win: {other:?}")),
            }
            let mut zone = ZoneP::new();
            zone.add_all_orders(witness_cells(witness));
            zone.union_with(&super::r3_zone::ep1(state.board(), attacker));
            computed.insert(key, zone);
            Ok(())
        }
        ProofKind::AndOverloadLeaf => {
            // Re-derived from the verifier's OWN enumeration: three or more
            // pairwise-disjoint plan families, and the defender cannot win
            // this turn.
            if super::r3_zone::defender_wins_now(state, attacker) {
                return Err("an overload leaf with the defender able to win this turn".into());
            }
            let families = super::r3_zone::plan_families(state.board(), attacker);
            if !min_hitting_set_exceeds_two(&families) {
                return Err(format!(
                    "an overload leaf with {} plan families that two stones can hit",
                    families.len()
                ));
            }
            let mut zone = ZoneP::new();
            for family in &families {
                zone.add_all_orders(family.iter().copied());
            }
            zone.union_with(&super::r3_zone::ep1(state.board(), attacker));
            computed.insert(key, zone);
            Ok(())
        }
        ProofKind::OrStep { witness } => {
            // The move is regenerated by the verifier's own policy code.
            let moves = super::r3_zone::threat_moves(state, attacker, policy);
            if !moves.contains(witness) {
                return Err(format!(
                    "the OR step's witness {witness:?} is not a policy move of the position"
                ));
            }
            super::r3_zone::r3_apply(state, witness);
            let child = node
                .children
                .first()
                .map(|(_, key)| *key)
                .ok_or("an OR step without its child")?;
            verify_node(state, attacker, child, nodes, computed, policy)?;
            super::r3_zone::r3_undo(state, witness);
            // AT-1: child zone + the move's cells + this node's EP-1.
            let mut zone = computed
                .get(&child)
                .expect("the child was verified before its parent")
                .clone();
            zone.add_all_orders(turn_cells(witness));
            zone.union_with(&super::r3_zone::ep1(state.board(), attacker));
            zone.assert_invariants();
            computed.insert(key, zone);
            Ok(())
        }
        ProofKind::AndStep => {
            // The defender-wins check, at EVERY AND node.
            if super::r3_zone::defender_wins_now(state, attacker) {
                return Err("an AND node where the defender wins this turn".into());
            }
            // The tree's child set must be exactly the blocking pairs —
            // re-derived independently — and every OTHER legal turn must
            // concretely resolve as an attacker win.
            let blocking = super::r3_zone::blocking_pairs(state, attacker);
            let tree_pairs: Vec<Turn> = node.children.iter().map(|(t, _)| *t).collect();
            if tree_pairs != blocking {
                return Err(format!(
                    "the AND node's child set ({}) is not the blocking pairs ({})",
                    tree_pairs.len(),
                    blocking.len()
                ));
            }
            let mut child_zone = ZoneP::new();
            for (turn, child) in &node.children {
                super::r3_zone::r3_apply(state, turn);
                verify_node(state, attacker, *child, nodes, computed, policy)?;
                child_zone.union_with(
                    computed
                        .get(child)
                        .expect("the child was verified before its parent"),
                );
                super::r3_zone::r3_undo(state, turn);
            }
            // The non-edges: every legal turn that is NOT a blocking pair
            // must resolve by the least surviving plan's completion.
            let turns = pistol_core::generate_turns(state)
                .map_err(|error| format!("generate_turns refused an AND node: {error}"))?;
            for turn in turns {
                if blocking.contains(&turn) {
                    continue;
                }
                resolve_non_edge(state, attacker, &turn)?;
            }
            // DT-1: the union of child zones, T3-1, EP-1.
            let mut zone = child_zone;
            let mut threat_cells = Vec::new();
            super::r3_zone::threat_cells(state, attacker, &mut threat_cells);
            zone.add_all_orders(threat_cells);
            zone.union_with(&super::r3_zone::ep1(state.board(), attacker));
            zone.assert_invariants();
            computed.insert(key, zone);
            Ok(())
        }
    }
}

/// A non-blocking defender turn resolves as an attacker win: the least
/// surviving plan's completion, applied and rule-2-checked through
/// pistol-core.
fn resolve_non_edge(state: &GameState, attacker: Player, turn: &Turn) -> Result<(), String> {
    let mut applied = state.clone();
    applied
        .make_turn(*turn)
        .map_err(|error| format!("a legal defender turn failed to apply: {error}"))?;
    if let pistol_core::Outcome::Win { winner, .. } = applied.outcome() {
        if winner != attacker {
            return Err(format!(
                "a non-tree defender turn {turn:?} WINS the game for the defender — the defender-win check missed it"
            ));
        }
        unreachable!("the attacker cannot complete six on the defender's turn");
    }
    // The least surviving plan, by (axis, start).
    let families = super::r3_zone::plan_families(applied.board(), attacker);
    let surviving: Vec<_> = families
        .into_iter()
        .filter(|family| family.iter().all(|at| !applied.board().is_occupied(*at)))
        .collect();
    if surviving.is_empty() {
        return Err(format!(
            "the non-tree turn {turn:?} is not a blocking pair but leaves no surviving plan — it WAS one"
        ));
    }
    let least = surviving.iter().min().expect("surviving is non-empty");
    let completion = least.to_vec();
    let turn = if completion.len() == 1 {
        Turn::Single(completion[0])
    } else {
        Turn::pair(completion[0], completion[1])
            .expect("a family of at most two cells holds distinct cells")
    };
    let mut finished = applied;
    finished
        .make_turn(turn)
        .map_err(|error| format!("the surviving plan's completion is illegal: {error}"))?;
    match finished.outcome() {
        pistol_core::Outcome::Win { winner, .. } if winner == attacker => Ok(()),
        other => Err(format!(
            "the surviving plan's completion does not win after {turn:?}: {other:?}"
        )),
    }
}

/// The registered re-derivation (design §7b): the exact minimum hitting
/// set over the plan families EXCEEDS two — no single cell and no pair of
/// cells hits every family. Pairwise-disjoint-3 (the earlier reading) is
/// sufficient but not necessary: a family hypergraph with matching number 2
/// can still have covering number 3, and a legitimate overload leaf in
/// that gap would have failed the verifier. The enumeration is exact and
/// small: families of at most two cells, a universe of at most a dozen.
fn min_hitting_set_exceeds_two(families: &[Vec<Coord>]) -> bool {
    if families.is_empty() {
        return false;
    }
    let universe: Vec<Coord> = {
        let mut cells: Vec<Coord> = families.iter().flat_map(|f| f.iter().copied()).collect();
        cells.sort_unstable();
        cells.dedup();
        cells
    };
    let hits_all = |cells: &[Coord]| -> bool {
        families
            .iter()
            .all(|family| cells.iter().any(|c| family.contains(c)))
    };
    // Sizes 0 and 1 first, then every pair.
    if hits_all(&[]) {
        return false;
    }
    if universe.iter().any(|&c| hits_all(&[c])) {
        return false;
    }
    for i in 0..universe.len() {
        for j in i + 1..universe.len() {
            if hits_all(&[universe[i], universe[j]]) {
                return false;
            }
        }
    }
    true
}

fn witness_turn(witness: &pistol_solver::WinWitness) -> Turn {
    match *witness {
        pistol_solver::WinWitness::OnePly { at, .. } => Turn::Single(at),
        pistol_solver::WinWitness::Pair { first, second, .. } => {
            Turn::pair(first, second).expect("the witness's cells are distinct")
        }
    }
}

fn witness_cells(witness: &pistol_solver::WinWitness) -> [Coord; 2] {
    match *witness {
        pistol_solver::WinWitness::OnePly { at, .. } => [at, at],
        pistol_solver::WinWitness::Pair { first, second, .. } => [first, second],
    }
}

fn turn_cells(turn: &Turn) -> [Coord; 2] {
    match turn {
        Turn::Single(at) => [*at, *at],
        Turn::Pair(first, second) => [*first, *second],
    }
}
