use crate::corpus::emit::Fixture;

use super::config::RandomOpeningsConfig;
use super::{Book, BookVersion};

/// v1's preamble, frozen: the committed fixture's bytes are pinned by a test
/// that regenerates them, so a word changed here is a red test rather than a
/// silent edit of the artifact every closed verdict was taken over.
const V1_PREAMBLE: &[&str] = &[
    "pistol random opening book, v1 — the arena's PRIMARY SPRT book.",
    "",
    "Pinned by SHA-256 in crates/pistol-cli/tests/random_openings_document_tests.rs",
    "(RANDOM_OPENINGS_V1_SHA256), and regenerated byte for byte from the config named",
    "below by `random_openings_v1_is_what_this_build_produces` in the same file. This",
    "book has no external input, so \"the committed bytes are the bytes this build",
    "writes\" is a test rather than an errand (docs/decisions.md D-152, D-177).",
    "",
    "One position per line, in the canonical move-list encoding (docs/decisions.md",
    "D-6) — the exact tail the `position` verb takes. There is NO commentary column:",
    "these positions have no provenance beyond the parameters below, and a column that",
    "said nothing would invite a reader to look for meaning in it.",
    "",
    "WHY A RANDOM BOOK IS THE PRIMARY ONE. The research report's Deliverable 4",
    "prescribes synthetic openings; pairing neutralises whatever per-opening bias any",
    "one of these carries, since both engines play both seats of every one; and the",
    "supply of distinct games is unbounded, where a corpus book is capped by the",
    "corpus. WP-1.2a's openings_v1.txt is retained as the realism cross-check suite",
    "and is not retired (docs/decisions.md D-175).",
    "",
    "NO BALANCE FILTER, and the reason is arithmetic rather than a judgement. A turn",
    "places two stones, so a mate in one TURN needs four own stones already in a",
    "six-window and a mate in one PLY needs five; at five stones the largest holding",
    "is three. No position in this file holds a mate in one for either side, so there",
    "is nothing for a filter to remove — and no engine was consulted to decide that,",
    "which is what keeps this a fixture rather than a book under CLAUDE.md rule 8",
    "(docs/decisions.md D-151, D-175). The question reopens if k grows.",
];

/// v2's preamble. It states what v1's cannot: why a second book exists, that
/// v1 is retired for governed use, and where this book's size and its consumed
/// ranges are recorded.
const V2_PREAMBLE: &[&str] = &[
    "pistol random opening book, v2 — the successor to the spent v1 book.",
    "",
    "Pinned by SHA-256 in crates/pistol-cli/tests/random_openings_document_tests.rs",
    "(RANDOM_OPENINGS_V2_SHA256), and regenerated byte for byte from the config named",
    "below by `random_openings_v2_is_what_this_build_produces` in the same file. This",
    "book has no external input, so \"the committed bytes are the bytes this build",
    "writes\" is a test rather than an errand (docs/decisions.md D-152, D-177).",
    "",
    "One position per line, in the canonical move-list encoding (docs/decisions.md",
    "D-6) — the exact tail the `position` verb takes. There is NO commentary column:",
    "these positions have no provenance beyond the parameters below, and a column that",
    "said nothing would invite a reader to look for meaning in it.",
    "",
    "WHY THERE IS A SECOND BOOK. Every slice of random_openings_v1.txt is consumed",
    "(docs/decisions.md D-491, D-492), so v1 is RETIRED FOR GOVERNED USE: it stays",
    "readable as the artifact the closed SPRT verdicts were taken over, and no new",
    "pre-registration may draw a slice from it. This file is where the fresh slices",
    "come from (docs/decisions.md D-505).",
    "",
    "WHAT \"FRESH\" MEANS HERE, EXACTLY. It is a claim about RANGES: a different seed",
    "draws a different stream, so no range of this file is a range of v1 and no",
    "governed run over it can be a re-read of a consumed sample. It is NOT a claim",
    "that no individual position appears in both books — both draw independently",
    "from ONE finite pool, so a small overlap is what independent drawing gives and",
    "is not evidence of anything. The overlap is MEASURED, pinned by a test, and its",
    "arithmetic is in docs/experiments/book_v2_registration.md; a filter against v1",
    "was declined because it would make this file's bytes depend on another file's,",
    "and a fixture reproducible only from its own header is the property D-147 and",
    "D-177 exist to keep.",
    "",
    "ITS SIZE IS REGISTERED WITH GROUNDS and is not a round number: the grounds are",
    "in docs/experiments/book_v2_registration.md, and the ledger of which ranges have",
    "been consumed is docs/book_v2_ledger.md. A book sized to the expected n is a book",
    "that runs out mid-run, which is the failure the registration exists to prevent.",
    "",
    "NO BALANCE FILTER, and the reason is arithmetic rather than a judgement. A turn",
    "places two stones, so a mate in one TURN needs four own stones already in a",
    "six-window and a mate in one PLY needs five; at five stones the largest holding",
    "is three. No position in this file holds a mate in one for either side, so there",
    "is nothing for a filter to remove — and no engine was consulted to decide that,",
    "which is what keeps this a fixture rather than a book under CLAUDE.md rule 8",
    "(docs/decisions.md D-151, D-175). The question reopens if k grows.",
];

/// The whole file, ready to write.
///
/// The preamble is the one part that differs between books, because it names
/// the book's own role, its own pinning test and its own standing. Everything
/// below it is generated from the config and the run, so the two arms cannot
/// drift in what they REPORT — only in what they SAY.
pub fn render(config: &RandomOpeningsConfig, book: &Book) -> String {
    let mut fixture = Fixture::new(match config.generate.book {
        BookVersion::V1 => V1_PREAMBLE,
        BookVersion::V2 => V2_PREAMBLE,
    });
    fixture.gap();
    fixture.note("How a position was made:");
    fixture.param("k_stones", config.generate.k_stones);
    fixture.param("n_openings", config.generate.n_openings);
    fixture.param("max_radius", config.generate.max_radius);
    fixture.param("seed", config.generate.seed);
    fixture.param("rng", "splitmix64");
    fixture.param("draw", "uniform_over_the_unused_cells_of_the_ball");
    fixture.param("dedupe", "canonical_form_over_the_12_lattice_symmetries");
    fixture.param("on_collision", "discard_the_candidate_and_draw_the_next");
    fixture.param("emission_order", "generation_order");
    fixture.derived("turn_structure", turn_structure(config.generate.k_stones));
    fixture.derived("ball_cells", book.ball_cells);
    fixture.derived("candidates_drawn", book.candidates_drawn);
    fixture.derived("symmetry_collisions", book.symmetry_collisions);
    fixture.derived("openings", book.openings.len());

    fixture.gap();
    fixture.note("max_radius is a GENERATION knob and is NOT the legal radius. Game rule 5's");
    fixture.note("LEGAL_RADIUS is a pinned constant in pistol-core and is never a knob; this");
    fixture.note("number only says how far from the ORIGIN a sampled stone may land. Every");
    fixture.note("placement is asked of pistol-core as it is made, at its own point in the");
    fixture.note("sequence, and a stone the rules refuse ends the run (docs/decisions.md D-177).");

    fixture.gap();
    fixture.note("The seed is the only reason these positions and not others, so it is stated");
    fixture.note("here as an input. There is no path, no timestamp and no hostname anywhere in");
    fixture.note("this file: the same config gives the same bytes on any machine");
    fixture.note("(CLAUDE.md rule 4).");
    fixture.note("");
    fixture.note("Emission order is GENERATION order, and that is deliberate. The draws are");
    fixture.note("independent, so a prefix of this file is already a sample; sorting it by");
    fixture.note("anything — coordinates, digest — would make a prefix a slice of whatever was");
    fixture.note("sorted on instead (docs/decisions.md D-143's argument, in a book that gets it");
    fixture.note("for free).");

    for opening in &book.openings {
        fixture.line(&opening.tail);
    }
    fixture.render()
}

/// The colours of a `k`-stone opening, as a header states them.
///
/// Read off game rule 3 rather than tabulated: turn 1 is one stone by P1, and
/// every turn after is two by whoever is to move.
fn turn_structure(k_stones: usize) -> String {
    let mut sides = vec!["p1@origin".to_string()];
    let mut placed = 1;
    let mut mover = "p2";
    while placed < k_stones {
        sides.push(format!("{mover},{mover}"));
        placed += 2;
        mover = if mover == "p2" { "p1" } else { "p2" };
    }
    sides.join(",")
}
